
FAIL event.intercept() should abort if the handler throws assert_equals: expected "#1" but got ""

